export const CONSTANTS = {
  BUTTON_BACKGROUND_SECONDARY: "#114B5F",
  BUTTON_BACKGROUND_PRIMARY: "#7d5fff",

  BACKGROUND_COLOR_PRIMARY: "#82ccdd",
  BACKGROUND_COLOR_SECONDARY: "#355070",

  COLOR_PRIMARY: "#E4FDE1",
  COLOR_SECONDARY: "#114B5F",
};
